// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stat struct {
	ID          int64              `json:"id"`
	UrlID       int64              `json:"url_id"`
	Count       pgtype.Int4        `json:"count"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
}

type Url struct {
	ID          int64              `json:"id"`
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
