// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_code, original_url)
VALUES ($1, $2)
RETURNING id, short_code, original_url, created_at
`

type CreateURLParams struct {
	ShortCode   string `json:"short_code"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getStatsByCode = `-- name: GetStatsByCode :one
SELECT 
    u.id, u.short_code, u.original_url, u.created_at,
    COALESCE(s.count, 0) AS click_count,
    s.last_updated
FROM urls u
LEFT JOIN stats s ON u.id = s.url_id
WHERE u.short_code = $1
`

type GetStatsByCodeRow struct {
	ID          int64              `json:"id"`
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ClickCount  int32              `json:"click_count"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
}

func (q *Queries) GetStatsByCode(ctx context.Context, shortCode string) (GetStatsByCodeRow, error) {
	row := q.db.QueryRow(ctx, getStatsByCode, shortCode)
	var i GetStatsByCodeRow
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ClickCount,
		&i.LastUpdated,
	)
	return i, err
}

const getURLByCode = `-- name: GetURLByCode :one
SELECT id, short_code, original_url, created_at FROM urls
WHERE short_code = $1 LIMIT 1
`

func (q *Queries) GetURLByCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listURL = `-- name: ListURL :many
SELECT 
    u.id, u.short_code, u.original_url, u.created_at,
    COALESCE(s.count, 0) AS click_count
FROM urls u
LEFT JOIN stats s ON u.id = s.url_id
ORDER BY u.created_at DESC
`

type ListURLRow struct {
	ID          int64              `json:"id"`
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ClickCount  int32              `json:"click_count"`
}

func (q *Queries) ListURL(ctx context.Context) ([]ListURLRow, error) {
	rows, err := q.db.Query(ctx, listURL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLRow
	for rows.Next() {
		var i ListURLRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.CreatedAt,
			&i.ClickCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStats = `-- name: UpsertStats :exec
INSERT INTO stats (url_id, count)
VALUES ($1, 1)
ON CONFLICT (url_id)
DO UPDATE SET 
    count = stats.count + 1,
    last_updated = NOW()
`

func (q *Queries) UpsertStats(ctx context.Context, urlID int64) error {
	_, err := q.db.Exec(ctx, upsertStats, urlID)
	return err
}
